<?php
/**
 * Gift Card final price template
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>

<?php if (!$block->getSaleableItem()->getData('is_custom_allowed')) :?>
    <?php if ($block->hasSpecialPrice()) :?>
        <span class="special-price">
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
        <span class="old-price">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => false
            ]); ?>
        </span>
    <?php else :?>
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    <?php endif; ?>
<?php else: ?>
    <?= __("Custom Amount") ?>
<?php endif; ?>
